/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrame;
import Farm.*;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author alvin
 */
public class JFarm extends javax.swing.JFrame {
    
    private int rows = 5;
    private int columns = 5;
    private int g = 10;
    private int w = 8;
    private int d = 7;
    NewJFrame l = new NewJFrame();
    Celdas[][] Cuadrado;
    

    /**
     * Creates new form Farm
     */
    public JFarm() {
        initComponents();
        //this.setLocationRelativeTo(null);
        this.setSize(670, 550);
        MatrizCuadrado();
        
    }
    
    public JButton hola(){
        return null;
    }
    public void MatrizCuadrado(){
        int posicionX = 100;
        int posicionY = 70;
        Object h = null;
        Cuadrado = new Celdas[rows][columns];
        
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                generarCelda(i,j);
                Cuadrado[i][j].setBounds(posicionX, posicionY, 80, 80);
                Cuadrado[i][j].generarCeldas();
                jPanel1.add(Cuadrado[i][j]);
                posicionX+=90;
            }
            posicionX=100;
            posicionY+=90;
        }
    }
    
    private void generarCelda(int i, int j){
        
        
        int aleatorio = ((int)(Math.random()*100)+1);
        
        if (aleatorio>60 && aleatorio <= 100) {
            if (w != 0) {
            Cuadrado[i][j] = new Water();
            /*Cuadrado[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicjed(java.awt.event.MouseEvent event){
                    Texto label = new Texto("Hola");
                    l.setVisible(true);
                }
            });*/
            w--;
            }
            else if (g != 0){
            Cuadrado[i][j] = new Grama();
            g--;
            }
            else if (d != 0){
            Cuadrado[i][j] = new Desert();
            d--;
            }
            else {
                
            }
        }
        else if (aleatorio>25 && aleatorio <= 60) {
            if (g != 0){
            Cuadrado[i][j] = new Grama();
            g--;
            }
            else if (w != 0) {
            Cuadrado[i][j] = new Water();
            w--;
            }
            else if (d != 0){
            Cuadrado[i][j] = new Desert();
            d--;
            }
            else {
                
            }
        }
        else if (aleatorio>0 && aleatorio <= 25) {
            if (d != 0){
            Cuadrado[i][j] = new Desert();
            d--;
            }
            else if (w != 0) {
            Cuadrado[i][j] = new Water();
            w--;
            }
            else if (g != 0){
            Cuadrado[i][j] = new Grama();
            g--;
            }
            else {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFarm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFarm().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
